[build]
command = "for link in $(find . -maxdepth 1 -type l -ls | cut -f \"28,30-\" -d \" \" | cut -c 2- | sed \"s/ /-\\//\"); do echo \"[[redirects]]\\n  from = \\\"$(echo $link | cut -f 1 -d \"-\")\\\"\\n  to = \\\"$(echo $link | cut -f 2 -d \"-\")\\\"\\n\\n\" \>\> Netlify.toml; done
"
