[build]
command = "for link in $(find . -maxdepth 1 -type l -ls | grep -e \"/.*\" -o | sed \"s/ -> /-\\//\"); do echo $link; sed -i \"$ a [[redirects]]\\n  from = \\\"$(echo $link | cut -f 1 -d \"-\")*\\\"\\n  to = \\\"$(echo $link | cut -f 2 -d \"-\"):splat\\\"\\n  status = 200\\n  force = true \\n\\n\" netlify.toml; done; echo \"$(cat netlify.toml)\""
